# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

    cooldown:
      # https://blog.yossarian.net/2025/11/21/We-should-all-be-using-dependency-cooldowns
      # Cooldowns protect against supply chain attacks by avoiding the
      # highest-risk window immediately after new releases.
      default-days: 14
