[project]
name = "daemonizer"
version = "1.0.0"
description = "Lib to daemonize programs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "distro>=1.9.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]

[tool.uv]
package = true
exclude-newer = "5 days"  # https://docs.astral.sh/uv/reference/settings/#exclude-newer
